#!/bin/bash

COMMIT_MSG=$(cat "$1")

REGEXP="^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+\))?(!)?:\ .+"

if [[ ! $COMMIT_MSG =~ $REGEXP ]]; then
    echo "Invalid commit message"
    exit 1
fi
