#!/bin/bash

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(ts|tsx|js|jsx)$')

if [ -z "$STAGED_FILES" ]; then
    exit 0
fi

bun x @biomejs/biome check --write --staged

bun x tsc --noEmit

bun x knip

bun test

git add $STAGED_FILES
